# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyInsight' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyInsight
  pod 'Masonry' # 约束布局
  pod 'MBProgressHUD' # 菊花加载
  pod 'SWRevealViewController' # 侧边抽屉
  pod 'BaiduMapKit' #百度地图SDK
  pod 'GoogleMaps' # Goole地图
  pod 'BabyBluetooth' # 蓝牙
  pod 'AFNetworking' # 网络请求
  pod 'ReactiveCocoa','~>2.1.8' # 响应式编程
  
  pod 'MQTTClient'
  pod 'MQTTClient/Websocket'
  pod 'SocketRocket'
  # iOS之MQTT简单使用 https://www.jianshu.com/p/a12cb037dff5
  # iOS MQTT----MQTTClient实战-看这篇的就够了 https://www.jianshu.com/p/80ea4507ca74
  
  #pod 'AsyncDisplayKit'
  
  # 微信第三方登录
  pod 'WechatOpenSDK'
  # AppID:wxd0f6b34b0b7430a4
  # AppSecret:1e860f261f083d47afcbe5305541d4b6
  
  target 'MyInsightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyInsightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
