# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyInsight_S' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyInsight_S

  target 'MyInsight_STests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'Alamofire', '~> 4.5' # 网络请求
    #pod 'SnapKit', '~> 4.0.0' # 约束布局
    
    
  end

  target 'MyInsight_SUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
