# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyInsight_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyInsight_Swift
  pod 'Alamofire' # 网络请求工具
  pod 'SnapKit'   # 代码约束布局
  

  target 'MyInsight_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyInsight_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
