# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArtBox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArtBox
  pod 'Masonry' # 约束布局
  pod 'AFNetworking' # 网络请求
  
  
  
  target 'ArtBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtBoxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
